### ISSUE TITLE
Tooltips worden niet in chrome weergegeven

### ISSUE THREAD

**Issue by robertjuh** [nsteijaert/HZ#15]
tooltips inmiddels gefixt en werken nu in firefox en chrome.
![tooltipsfixed](https://cloud.githubusercontent.com/assets/1580644/8374819/cc93da1a-1bf8-11e5-99bb-df3ef7a7e0ff.png)

Opmaak moet wel veranderd worden(groen is niet zo mooi) en bij onHover komt de default tooltip ook nog eens opduiken (dubbele tooptips)

**Comment by robertjuh** [comment]
eventueel fade in/fade out

**Comment by Gymnasiast** [comment]
Goed gedaan. :-)
Kun je de code opsturen? Dan integreer ik hem.
