### ISSUE TITLE
Hoofdcontext heeft als tooltip 'undefined'

### ISSUE THREAD

**Issue by Gymnasiast** [nsteijaert/HZ#20]

**Comment by robertjuh** [comment]
![undefined_tooltip](https://cloud.githubusercontent.com/assets/1580644/9633278/48eee172-518c-11e5-92cb-7d78b4f8c398.png)

**Comment by robertjuh** [comment]
![hallo](https://cloud.githubusercontent.com/assets/1580644/9633329/9b27d034-518c-11e5-8bbb-d79a64eb57e9.png)

**Comment by robertjuh** [comment]
d.tooltip lijkt niet te bestaan bij de hoofdcontexten. Volstaat dit ook? Of langbijschrift of innerHTML?

**Comment by Gymnasiast** [comment]
Langbijschrift zou moeten worden omgezet in d.tooltip, wat bij de hoofdcontext blijkbaar niet gebeurt. d.bijschrift wordt gebruikt als zichtbare kop en is een ingekorte versie van langbijschrift. d.bijschrift volstaat dus helaas niet.
