### ISSUE TITLE
Dataset moet niet meer hard-coded staan

### ISSUE THREAD

**Issue by robertjuh** [nsteijaert/HZ#21]
Als de code uitgechekt wordt, werkt het niet gelijk op andere systemen en moet de URL in SPARQLConnection.class handmatig aangepast worden.

**Comment by Gymnasiast** [comment]
Grotendeels opgelost. 'Eigenschap-3A' en '/ds' staan nog gehardcoded, maar het adres van de Mediawiki ('127.0.0.1/mediawiki') niet meer.
