### ISSUE TITLE
Visualisatie wordt vaak buiten grenzen SVG-element gerenderd

### ISSUE THREAD

**Issue by Gymnasiast** [nsteijaert/HZ#5]

**Comment by robertjuh** [comment]
Zoals bij den het geval:

http://127.0.0.1/mediawiki2/index.php/Speciaal:EMontVisualisator/toon/Oesterdam_veiligheidsbuffer_experience

http://127.0.0.1/mediawiki2/index.php/Speciaal:EMontVisualisator/toon/Waterdunen_experience

http://127.0.0.1/mediawiki2/index.php/Speciaal:EMontVisualisator/toon/Hoogwaterbescherming_practice

**Comment by robertjuh** [comment]
voorveeld van bouding box: http://bl.ocks.org/mbostock/1129492

( in dit voorbeeld worden elementen niet meer buiten het voorbeeld getekend
