### ISSUE TITLE
IE's worden soms over elkaar getekend

### ISSUE THREAD

**Issue by Gymnasiast** [nsteijaert/HZ#7]

**Comment by robertjuh** [comment]
http://127.0.0.1/mediawiki2/index.php/Speciaal:EMontVisualisator/toon/Holistic_analysis_of_wicked_problems_practice

Bij deze worden ze overelkaar heen getekend

**Comment by robertjuh** [comment]
Mogelijke oplossing: http://marvl.infotech.monash.edu/webcola/examples/nonoverlapping.html

"  
function removeOverlaps(rects) {
    var rs = new Array(rects.length);
    var dims = [];
    rects.forEach(function (r, i) {
        var x = r.attr('x'), y = r.attr('y'), w = r.attr('width'), h = r.attr('height');
        dims.push({ x: x, y: y, w: w, h: h });
        rs[i] = new cola.vpsc.Rectangle(x, x + w, y, y + h);
    });
    undoStack.push(dims);
    cola.vpsc.removeOverlaps(rs);
    rects.forEach(function (r, i) {
        var t = rs[i];
        if (animate) {
            r.animate().move(t.x, t.y);
        } else {
            r.move(t.x, t.y);
        }
    });
    //o.vs.forEach(function (v, i) {
    //    v.id = i;
    //});
    //o.cs.forEach(function (c) {
    //    var l = rs[c.left.id];
    //    var r = rs[c.right.id];
    //    draw.line(l.cx(), l.cy(), r.cx(), r.cy()).stroke({ width: 1, color: "orange" });
    //});
}
"

**Comment by Gymnasiast** [comment]
Mogelijk opgelost door SVG meer ruimte te geven.
